const DOORS=[
  {id:1, name:'Прага', series:'Элит', purpose:'дом', price:109900, finish:'venge', glass:'none', handle:'short', flag:null, popular:102, tags:['Скрытые петли','Терморазрыв']},
  {id:2, name:'Вена', series:'Элит', purpose:'тамбур', price:87400, finish:'venge', glass:'forge', handle:'long', flag:'Хит', popular:48, tags:['Скрытые петли','Терморазрыв']},
  {id:3, name:'Рим', series:'Элит', purpose:'тамбур', price:69400, finish:'oak', glass:'mirror', handle:'long', flag:'Рекомендуем', popular:58, tags:['Скрытые петли','Терморазрыв']},
  {id:4, name:'Милан', series:'Комфорт', purpose:'квартира', price:37900, finish:'graphite', glass:'panel', handle:'short', flag:'Новинка', popular:101, tags:['Двойной контур','Guardian']},
  {id:5, name:'Турин', series:'Комфорт', purpose:'квартира', price:37900, finish:'black', glass:'panel', handle:'short', flag:null, popular:46, tags:['Двойной контур','Guardian']},
  {id:6, name:'Верона', series:'Элит', purpose:'офис', price:96400, finish:'cream', glass:'none', handle:'short', flag:'Рекомендуем', popular:56, tags:['Скрытые петли','Терморазрыв']},
  {id:7, name:'Сиена', series:'Комфорт', purpose:'квартира', price:37900, finish:'graphite', glass:'none', handle:'short', flag:'Элит', popular:38, tags:['Двойной контур','Guardian']},
  {id:8, name:'Пиза', series:'Элит', purpose:'офис', price:123400, finish:'oak', glass:'panel', handle:'long', flag:null, popular:74, tags:['Скрытые петли','Терморазрыв']},
  {id:9, name:'Парма', series:'Стандарт', purpose:'квартира', price:24400, finish:'white', glass:'panel', handle:'short', flag:'Хит', popular:54, tags:['Двойной контур','Guardian']},
  {id:10, name:'Лукка', series:'Премиум', purpose:'квартира', price:55900, finish:'graphite', glass:'forge', handle:'long', flag:'Новинка', popular:112, tags:['Терморазрыв','Ковка']},
  {id:11, name:'Лион', series:'Элит', purpose:'квартира', price:78400, finish:'walnut', glass:'mirror', handle:'long', flag:'Рекомендуем', popular:5, tags:['Скрытые петли','Терморазрыв']},
  {id:12, name:'Ницца', series:'Стандарт', purpose:'тамбур', price:24400, finish:'concrete', glass:'none', handle:'short', flag:'Рекомендуем', popular:55, tags:['Двойной контур','Guardian']},
  {id:13, name:'Канны', series:'Элит', purpose:'офис', price:100900, finish:'graphite', glass:'arch', handle:'long', flag:'Новинка', popular:76, tags:['Скрытые петли','Терморазрыв']},
  {id:14, name:'Бордо', series:'Элит', purpose:'квартира', price:73900, finish:'oak', glass:'vitrage', handle:'short', flag:'Элит', popular:124, tags:['Скрытые петли','Терморазрыв']},
  {id:15, name:'Реймс', series:'Элит', purpose:'тамбур', price:145900, finish:'oak', glass:'panel', handle:'long', flag:null, popular:49, tags:['Скрытые петли','Терморазрыв']},
  {id:16, name:'Тулуза', series:'Элит', purpose:'тамбур', price:123400, finish:'venge', glass:'none', handle:'long', flag:'Новинка', popular:138, tags:['Скрытые петли','Терморазрыв']},
  {id:17, name:'Авиньон', series:'Элит', purpose:'дача', price:118900, finish:'concrete', glass:'forge', handle:'long', flag:'Новинка', popular:92, tags:['Скрытые петли','Терморазрыв']},
  {id:18, name:'Версаль', series:'Эконом', purpose:'дом', price:19900, finish:'oak', glass:'vitrage', handle:'long', flag:'Хит', popular:10, tags:['Витраж']},
  {id:19, name:'Шамони', series:'Премиум', purpose:'квартира', price:46900, finish:'walnut', glass:'arch', handle:'long', flag:'Рекомендуем', popular:19, tags:['Терморазрыв','Арка']},
  {id:20, name:'Мадрид', series:'Премиум', purpose:'квартира', price:60400, finish:'oak', glass:'forge', handle:'short', flag:null, popular:118, tags:['Терморазрыв','Ковка']},
  {id:21, name:'Толедо', series:'Элит', purpose:'тамбур', price:136900, finish:'venge', glass:'vitrage', handle:'short', flag:'Хит', popular:90, tags:['Скрытые петли','Терморазрыв']},
  {id:22, name:'Гранада', series:'Элит', purpose:'дом', price:100900, finish:'venge', glass:'arch', handle:'long', flag:null, popular:131, tags:['Скрытые петли','Терморазрыв']},
  {id:23, name:'Севилья', series:'Элит', purpose:'дом', price:150400, finish:'cream', glass:'none', handle:'short', flag:null, popular:80, tags:['Скрытые петли','Терморазрыв']},
  {id:24, name:'Малага', series:'Элит', purpose:'дача', price:91900, finish:'concrete', glass:'none', handle:'short', flag:'Хит', popular:65, tags:['Скрытые петли','Терморазрыв']},
  {id:25, name:'Валенсия', series:'Премиум', purpose:'дача', price:64900, finish:'black', glass:'mirror', handle:'short', flag:'Рекомендуем', popular:22, tags:['Терморазрыв','Зеркало']},
  {id:26, name:'Барселона', series:'Комфорт', purpose:'тамбур', price:33400, finish:'graphite', glass:'rect', handle:'short', flag:'Элит', popular:84, tags:['Двойной контур','Guardian']},
  {id:27, name:'Жирона', series:'Элит', purpose:'квартира', price:73900, finish:'graphite', glass:'vitrage', handle:'short', flag:'Рекомендуем', popular:50, tags:['Скрытые петли','Терморазрыв']},
  {id:28, name:'Порту', series:'Элит', purpose:'дом', price:91900, finish:'walnut', glass:'vitrage', handle:'short', flag:'Элит', popular:50, tags:['Скрытые петли','Терморазрыв']},
  {id:29, name:'Лиссабон', series:'Элит', purpose:'квартира', price:87400, finish:'cream', glass:'rect', handle:'short', flag:'Элит', popular:42, tags:['Скрытые петли','Терморазрыв']},
  {id:30, name:'Эвора', series:'Премиум', purpose:'дача', price:46900, finish:'cream', glass:'panel', handle:'long', flag:'Новинка', popular:123, tags:['Терморазрыв']},
  {id:31, name:'Синтра', series:'Элит', purpose:'дача', price:123400, finish:'black', glass:'vitrage', handle:'long', flag:'Рекомендуем', popular:26, tags:['Скрытые петли','Терморазрыв']},
  {id:32, name:'Брюгге', series:'Элит', purpose:'квартира', price:96400, finish:'venge', glass:'panel', handle:'short', flag:'Элит', popular:113, tags:['Скрытые петли','Терморазрыв']},
  {id:33, name:'Гент', series:'Премиум', purpose:'офис', price:64900, finish:'walnut', glass:'forge', handle:'long', flag:'Новинка', popular:83, tags:['Терморазрыв','Ковка']},
  {id:34, name:'Антверпен', series:'Комфорт', purpose:'дом', price:42400, finish:'black', glass:'none', handle:'long', flag:'Хит', popular:28, tags:['Двойной контур','Guardian']},
  {id:35, name:'Амстердам', series:'Премиум', purpose:'тамбур', price:55900, finish:'oak', glass:'vitrage', handle:'long', flag:'Хит', popular:108, tags:['Терморазрыв','Витраж']},
  {id:36, name:'Утрехт', series:'Элит', purpose:'квартира', price:105400, finish:'black', glass:'arch', handle:'short', flag:'Хит', popular:131, tags:['Скрытые петли','Терморазрыв']},
  {id:37, name:'Дельфт', series:'Элит', purpose:'тамбур', price:96400, finish:'walnut', glass:'arch', handle:'short', flag:null, popular:123, tags:['Скрытые петли','Терморазрыв']},
  {id:38, name:'Берлин', series:'Премиум', purpose:'дом', price:60400, finish:'black', glass:'vitrage', handle:'short', flag:null, popular:83, tags:['Терморазрыв','Витраж']},
  {id:39, name:'Мюнхен', series:'Эконом', purpose:'дача', price:19900, finish:'black', glass:'arch', handle:'short', flag:'Элит', popular:44, tags:['Арка']},
  {id:40, name:'Бонн', series:'Элит', purpose:'квартира', price:145900, finish:'cream', glass:'none', handle:'long', flag:'Элит', popular:97, tags:['Скрытые петли','Терморазрыв']},
  {id:41, name:'Кёльн', series:'Элит', purpose:'офис', price:87400, finish:'oak', glass:'arch', handle:'long', flag:'Элит', popular:86, tags:['Скрытые петли','Терморазрыв']},
  {id:42, name:'Дрезден', series:'Премиум', purpose:'дом', price:60400, finish:'concrete', glass:'none', handle:'long', flag:'Рекомендуем', popular:137, tags:['Терморазрыв']},
  {id:43, name:'Лейпциг', series:'Премиум', purpose:'квартира', price:64900, finish:'graphite', glass:'panel', handle:'long', flag:null, popular:91, tags:['Терморазрыв']},
  {id:44, name:'Цюрих', series:'Комфорт', purpose:'офис', price:33400, finish:'black', glass:'rect', handle:'short', flag:null, popular:93, tags:['Двойной контур','Guardian']},
  {id:45, name:'Берн', series:'Элит', purpose:'квартира', price:132400, finish:'oak', glass:'panel', handle:'long', flag:'Новинка', popular:111, tags:['Скрытые петли','Терморазрыв']},
  {id:46, name:'Базель', series:'Элит', purpose:'дача', price:91900, finish:'walnut', glass:'panel', handle:'long', flag:'Элит', popular:99, tags:['Скрытые петли','Терморазрыв']},
  {id:47, name:'Люцерн', series:'Премиум', purpose:'дом', price:46900, finish:'oak', glass:'mirror', handle:'short', flag:'Элит', popular:84, tags:['Терморазрыв','Зеркало']},
  {id:48, name:'Женева', series:'Элит', purpose:'квартира', price:118900, finish:'white', glass:'vitrage', handle:'short', flag:'Рекомендуем', popular:60, tags:['Скрытые петли','Терморазрыв']},
  {id:49, name:'Зальцбург', series:'Элит', purpose:'дача', price:73900, finish:'venge', glass:'mirror', handle:'long', flag:null, popular:67, tags:['Скрытые петли','Терморазрыв']},
  {id:50, name:'Грац', series:'Премиум', purpose:'квартира', price:60400, finish:'white', glass:'forge', handle:'long', flag:null, popular:112, tags:['Терморазрыв','Ковка']},
  {id:51, name:'Линц', series:'Элит', purpose:'дача', price:78400, finish:'black', glass:'vitrage', handle:'short', flag:'Хит', popular:124, tags:['Скрытые петли','Терморазрыв']},
  {id:52, name:'Будапешт', series:'Элит', purpose:'квартира', price:105400, finish:'concrete', glass:'forge', handle:'short', flag:'Хит', popular:19, tags:['Скрытые петли','Терморазрыв']},
  {id:53, name:'Сегед', series:'Элит', purpose:'дом', price:141400, finish:'concrete', glass:'vitrage', handle:'short', flag:null, popular:23, tags:['Скрытые петли','Терморазрыв']},
  {id:54, name:'Печ', series:'Элит', purpose:'дом', price:69400, finish:'graphite', glass:'none', handle:'short', flag:null, popular:128, tags:['Скрытые петли','Терморазрыв']}
];
